### ISSUE TITLE
Stuck on loading bar when opening WebUI

### ISSUE THREAD

**Issue by anLizard** [jbonjean/docker-public#3]
When I access the webUI, I get redirected to /indexstate-redirect for a moment, then to /playback.
But it only loads indefinitely there.

![image](https://user-images.githubusercontent.com/48686356/115542173-4c176200-a2a0-11eb-88b4-6c414bafac51.png)

I tried running the image two ways, first with docker-compose

```
version: "3"

networks:
  internal:

services:

  app:
    image: jbonjean/volumio:latest
    networks:
      - internal
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./music:/var/lib/mpd/music/:ro
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - HOST=http://localhost:3000/
      - PGID=1000
    devices:
      - /dev/null:/dev/snd
```

then as a command
```
docker run --restart=always -d --name volumio \
  -e HOST=http://192.168.1.1:3000 \
  -p 3000:3000 \
  -v ./data:/data \
  --device /dev/snd \
  jbonjean/volumio
```

But the results are the same both times. What am I doing wrong?
