### ISSUE TITLE
Missing multiroom audio on volumio

### ISSUE THREAD

**Issue by h4de5** [jbonjean/docker-public#4]
Hi,

I wanted to share some extended docker-compose file which includes more open ports + the service that uses it.
also I had issues with the `HOST` environment variable because album art and category icons did not show up correctly. I fixed this by using a simple post call to the volumio api which I also included in the docker-compose below.

what I still miss is a working multi-room setup. If I start the container in `network_mode: host`, it will find other volumio devices (and also get discovered) in the network. but in normal mode, it seems the mdns/avahi/zeroconf/whatever service is not correctly propagated to and from the container. would be great if somebody can help.

```yaml

version: "3.3"
services:
  volumio:
    restart: unless-stopped
    container_name: volumio
    environment:
      HOST: http://192.168.0.77:3000
    ports:
      - "3000:3000"
      # albumart - https://github.com/volumio/Volumio2/blob/7e4645db47770588c5bc6bde570a1e3a9e2917e0/app/plugins/miscellanea/albumart/config.json#L2
      - "3001:3001"
      # updater - https://github.com/volumio/Volumio2/blob/7e4645db47770588c5bc6bde570a1e3a9e2917e0/app/plugins/system_controller/updater_comm/index.js#L7
      - "3005:3005"
      # mpd - https://github.com/volumio/Volumio2/blob/7e4645db47770588c5bc6bde570a1e3a9e2917e0/app/plugins/music_service/mpd/lib/mpd.js#L31
      - "6600:6600"
      # mpd emulation - https://github.com/volumio/Volumio2/blob/7e4645db47770588c5bc6bde570a1e3a9e2917e0/app/plugins/user_interface/mpdemulation/index.js#L9
      - "6500:6500"
      # shairport - https://github.com/volumio/Volumio2/blob/7e4645db47770588c5bc6bde570a1e3a9e2917e0/app/plugins/music_service/airplay_emulation/shairport-sync.conf.tmpl#L33
      - "5555:5555"
      # sharepoint - https://github.com/volumio/Volumio2/blob/7e4645db47770588c5bc6bde570a1e3a9e2917e0/app/plugins/music_service/airplay_emulation/shairport-sync-reader/README.md#L16
      - "255:255"
      # upnp - https://github.com/volumio/Volumio2/blob/7e4645db47770588c5bc6bde570a1e3a9e2917e0/app/plugins/audio_interface/upnp/index.js#L9
      - "6599:6599"
      # debugger - https://github.com/volumio/Volumio2/blob/7e4645db47770588c5bc6bde570a1e3a9e2917e0/app/plugins/system_controller/volumio_command_line_client/commands/devmode.sh#L5
      # - "9229:9229"
    # network_mode: host
    volumes:
      - "/volume1/music:/var/lib/mpd/music:ro"
      - "./config:/data"
      - "./config/config.txt:/boot/config.txt"
      # for mdns/avahi
      - "/var/run/dbus:/var/run/dbus"
    devices:
      - /dev/snd
    image: jbonjean/volumio
    healthcheck:
      test:
        ["CMD-SHELL", "curl --fail http://localhost:3000/api/host || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # to properly set host variable after container start
  volumio-set-host:
    depends_on:
      volumio:
        condition: service_healthy
    container_name: volumio-set-host
    image: curlimages/curl:latest
    # set host variable from above
    command: curl -d "host=http://192.168.0.77" -X POST http://volumio:3000/api/host

```
