### ISSUE TITLE
Cross-Origin message in browser console

### ISSUE THREAD

**Issue by maxdd** [jbonjean/docker-public#7]
Hello,
thank you for making this image.
I started a container with the following command

```
docker run --restart=always -d --name volumio \
  -e HOST=http://192.168.1.52:3010 \
  -p 3010:3000 \
  -v /media/ubuntu/E432F8DB32F8B420/Audio/:/var/lib/mpd/music/:ro \
  -v /home/ubuntu/Desktop/volumio/data/:/data \
  --device /dev/snd \
  jbonjean/volumio
```
but while i can browse it nicely and keep receiving the following message in the console

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.1.52/api/host. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)`

this message is also most likely the reason why when I hit "play" button nothing happens.
Do you have any suggestion?

**Comment by maxdd** [comment]
even with those errors by using pulseaudio i was able to make it work

```
version: '3.2'

services:
  volumio:
    image: jbonjean/volumio
    container_name: volumio
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - /media/ubuntu/E432F8DB32F8B420/Audio/:/var/lib/mpd/music/Audio/:ro
      - /home/ubuntu/Music/:/var/lib/mpd/music/Music/:ro
      - /home/ubuntu/docker/volumio/data/:/data
      - /run/user/1000/pulse:/pulse:ro
    environment:
      - HOST=http://192.168.1.52:3000
      - PULSE_SERVER=unix:/pulse/native
      - PULSE_COOKIE_DATA=home/ubuntu/.config/pulse/cookie
      - HOST_USER=1000:1000
      - AUDIO_OUTPUT=pulse
    devices:
      - /dev/snd:/dev/snd
```

without pulseaudio i wasn't able to.
I opened a ticket here if you want to help

https://github.com/volumio/Volumio2/issues/2163
